### ISSUE TITLE
Action items for Nikolaus

### ISSUE THREAD

**Issue by alecive** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#54]
- [x] Mapping of book content with learning goals (very different from mapping chapter)
- [x] Confirm that the deadline is mid-May at least (draft in May 23rd , internal deadline in May 16th)
- [x] Fix issue #52 
- [x] Fix issue #50 
- [x] I think you should help @hayesbh  with the exercises because it is kinda difficult to extrapolate your opinion about it
- [x] Add the figures in the actuator chapter and fix the comments @alecive placed in  #47 
- [x] Take care of #46 
- [x] Take care of https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots/issues/60
