### ISSUE TITLE
Action items for Alessandro

### ISSUE THREAD

**Issue by alecive** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#55]
- [x] Take care of the damn figures 
- [x] Finish the force chapter 
- [x] Take care of #35 
- [x] Take care of #38
- [x] Take care of #59 
- [x] Take care of #45 
- [x] Finish the Kinematics Chapter and assign #46 to brad

**Comment by alecive** [comment]
Force chapter finalized in https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots/commit/765be78db2f172adb63025accd9883ef30367cbc

**Comment by alecive** [comment]
DONE
