### ISSUE TITLE
Tracker for the last pass of the book

### ISSUE THREAD

**Issue by alecive** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#62]
- [ ] Preface : @correll , @alecive, @crheckman, @hayesbh 
- [ ] Chapter 1 : @correll , @alecive , @crheckman, @hayesbh 
- [ ] Chapter 2 : @correll , @alecive, @crheckman, @hayesbh 
- [ ] Chapter 3 : @correll , @alecive, @crheckman, @hayesbh
- [ ] Chapter 4: @alecive, @correll, @hayesbh 
- [ ] Chapter 5: @alecive, @correll, @hayesbh 
- [ ] Chapter 6: @alecive, @correll
- [ ] Chapter 7: @alecive, @crheckman,  @correll 
- [ ] Chapter 8: @crheckman, @correll 
- [ ] Chapter 9: @crheckman, @correll 
- [ ] Chapter 10: @alecive
- [ ] Chapter 11: @crheckman 
- [ ] Chapter 12: @alecive, @correll
- [ ] Chapter 13: @alecive (within the next two days)
- [ ] Chapter 14: @alecive (within the next two days), @correll
- [ ] Chapter 15: @hayesbh, @crheckman (within the next few days), @correll
- [ ] Chapter 16: @hayesbh, @crheckman , @correll
- [ ] Chapter 17: @crheckman, @correll

- [ ] Appendix A:
- [ ] Appendix B: @correll
- [ ] Appendix C:
- [ ] Appendix D: @correll
- [ ] Appendix E:
- [ ] Appendix F: @correll

**Comment by alecive** [comment]
@crheckman @hayesbh please start to follow my lead (i.e. start after I finish my pass)

**Comment by crheckman** [comment]
@mmiles19 will be checking out Chapter 15.

**Comment by alecive** [comment]
Done!
